import type { Metadata } from "next";
import "./_style/globals.css";

export const metadata: Metadata = {
  title: "Maruf book store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
